Add early diagram
kookmin-sw/capstone-2023-43 pull request #3
Opened 2023-03-13 03:59 UTC by fmowl10

진행도 다이어그램
* 약추가
* 로그인
* 회원가입

구조 다이어그램
* 전체서비스 구조
* DB 스키마

2023-03-13 04:06 UTC, whdgmawkd commented
기획 초반 회의 내용 문서화 구조 확인했습니다.

2023-03-13 04:09 UTC, whdgmawkd reviewed
구조 설계 다이어그램 내용 확인 완료

2023-03-13 04:10 UTC, whdgmawkd requested changes
DB 스키마 수정 필요

2023-03-13 12:39 UTC, whdgmawkd commented
DB스키마에서
* Pill, MixTaboo는 관계형 DB에 들어가야 할 내용 RDS에 저장되는 것으로 다이어그램 업데이트 필요
* User는 인증에 필요한 uuid, name정도만 RDS에 보관하고 나머지 성별, 임신여부, 혈압 등등은 DocumentDB에서 관리하는 구조로 변경 필요

나머지 다이어그램은 회의 내용과 일치하는것으로 보임

2023-03-14 13:21 UTC, Cocozo reviewed
Pill 테이블에 약 복용 주기 테이블이 더 필요할 것 같습니다.
또한 MixTaboo의 내용은 주로 같이 복용하면 안되는 약들의 페어로 되어있어 해당 테이블의 제목을 조금 더 목적에 어울리는 제목으로 바꾸어야 되지 않을까 싶습니다

2023-03-17 07:03 UTC, whdgmawkd commented
Cognito에서 가져오는 정보:
- 이름
- 이메일
- 설별
- 생년월일

위 정보중 이메일은 RDS에 나머지는 DocumentDB에 들어가게 설계하도록 하겠습니다

2023-03-18 10:57 UTC, whdgmawkd approved these changes
변경사항 확인했습니다.

2023-03-18 11:02 UTC, merged